// Code generated by goctl. DO NOT EDIT!
// Source: op_account.proto

package server

import (
	"context"

	"github.com/reation/micro_service_account_service/account/internal/logic"
	"github.com/reation/micro_service_account_service/account/internal/svc"
	"github.com/reation/micro_service_account_service/protoc"
)

type AccountServer struct {
	svcCtx *svc.ServiceContext
	protoc.UnimplementedAccountServer
}

func NewAccountServer(svcCtx *svc.ServiceContext) *AccountServer {
	return &AccountServer{
		svcCtx: svcCtx,
	}
}

func (s *AccountServer) OpAccount(ctx context.Context, in *protoc.OpAccountRequest) (*protoc.OpAccountResponse, error) {
	l := logic.NewOpAccountLogic(ctx, s.svcCtx)
	return l.OpAccount(in)
}

func (s *AccountServer) GetAccount(ctx context.Context, in *protoc.GetAccountRequest) (*protoc.GetAccountResponse, error) {
	l := logic.NewGetAccountLogic(ctx, s.svcCtx)
	return l.GetAccount(in)
}
