package config

var (
	RETURN_STATE_NORMAL         int64 = 1
	RETURN_STATE_MONEY_LESS     int64 = 21
	RETURN_STATE_ERROR          int64 = 31
	RETURN_STATE_USER_NOT_FOUND int64 = 41
	RETURN_STATE_USER_UNUSUAL   int64 = 51
	RETURN_STATE_USER_FORZEN    int64 = 61
	RETURN_STATE_PASSWORD_WRONG int64 = 71
)
